import { Activity } from './types';

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: '1',
    code: 'SB-001',
    name: 'บลิค 4 สี',
    setName: 'ชุดฝึกสายตา A',
    description: 'กิจกรรมฝึกการจำแนกสีโดยใช้บลิค 4 สี เพื่อเพิ่มทักษะการรับรู้ทางสายตา',
    skills: ['Visual Discrimination', 'Focus / Concentration', 'Hand-Eye Co-ordination'],
    images: ['https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?w=200&h=200&fit=crop'],
    files: ['#'],
    driveUrls: ['https://drive.google.com/file/d/example1'],
    note: 'ใช้สำหรับเด็กอายุ 5-8 ปี',
    dateAdded: '2025-05-20',
  },
  {
    id: '2',
    code: 'SB-002',
    name: 'ต่อบลิคตามแบบ',
    setName: 'ชุดฝึกสายตา A',
    description: 'กิจกรรมต่อบลิคตามแบบที่กำหนด ฝึกทักษะการมองตามแบบ https://example.com/guide',
    skills: ['Visual Figure Ground', 'Spatial Awareness', 'Fine Motor กล้ามเนื้อนิ้วมือ'],
    images: [],
    files: ['#'],
    driveUrls: ['https://drive.google.com/file/d/example2'],
    note: '',
    dateAdded: '2025-05-21',
  },
  {
    id: '3',
    code: 'SB-003',
    name: 'ฟังแล้วทำ',
    setName: 'ชุดฝึกการฟัง B',
    description: 'กิจกรรมฝึกทักษะการฟังอย่างตั้งใจ โดยผู้สอนออกคำสั่งให้เด็กทำตาม',
    skills: ['ฟังอย่าง Focus', 'Auditory Memory', 'Inhibitory Control'],
    images: [],
    files: ['#'],
    driveUrls: ['https://drive.google.com/file/d/example3'],
    note: 'ให้เริ่มจากคำสั่งง่ายๆ ก่อน',
    dateAdded: '2025-05-22',
  },
  {
    id: '4',
    code: 'SB-004',
    name: 'จำลำดับภาพ',
    setName: 'ชุดฝึกความจำ C',
    description: 'ฝึกจำภาพตามลำดับที่แสดง แล้วเรียงลำดับใหม่ให้ถูกต้อง',
    skills: ['Visual Sequential Memory', 'Visual Working Memory', 'Cognitive'],
    images: [],
    files: ['#'],
    driveUrls: ['https://drive.google.com/file/d/example4'],
    note: 'มี 3 ระดับความยาก',
    dateAdded: '2025-05-23',
  },
  {
    id: '5',
    code: 'SB-005',
    name: 'ข้ามเส้นกลาง',
    setName: 'ชุดฝึกร่างกาย D',
    description: 'กิจกรรมเคลื่อนไหวร่างกายข้ามแนวกลางลำตัว เพื่อพัฒนาการประสานงานของสมองซีกซ้าย-ขวา',
    skills: ['Crossing the Midline', 'Hand-Eye Co-ordination', 'Spatial Awareness'],
    images: [],
    files: ['#', '#'],
    driveUrls: ['https://drive.google.com/file/d/example5'],
    note: 'ใช้เชือก/ริบบิ้นเป็นอุปกรณ์เสริม',
    dateAdded: '2025-05-24',
  },
  {
    id: '6',
    code: 'SB-006',
    name: 'อารมณ์หลากสี',
    setName: 'ชุดฝึกอารมณ์ E',
    description: 'กิจกรรมเรียนรู้อารมณ์ต่างๆ ผ่านการ์ดสีและการแสดงออกทางสีหน้า',
    skills: ['Emotions', 'Cognitive', 'Goal-Directed Persistence'],
    images: [],
    files: ['#'],
    driveUrls: ['https://drive.google.com/file/d/example6'],
    note: 'ชุดนี้มีการ์ดอารมณ์ 20 ใบ',
    dateAdded: '2025-05-25',
  },
];
